### ISSUE TITLE
AttributeError: 'EnergySystem' object has no attribute 'signals'

### ISSUE THREAD

**Issue by baumconsult** [oemof/oemof-examples#43] opened 2019-06-13 13:01 UTC
I just installed oemof v0.3.1 via Anaconda Promt and tried running basic_example.py. I modified only line 68 to filename = 'basic_example.csv' and stored this file in the same directory as the code. I get the error message shown in the headline. Here the screenshot from spyder:

![grafik](https://user-images.githubusercontent.com/38760674/59434338-abc29d80-8deb-11e9-8ca0-93a1a829943b.png)

**Comment by jakob-wo** [comment] 2019-06-13 13:58
Hi Michael,

I tried to reproduce what you did but I do not get an error mesage when running basic_example.py (oemof.solph\v0.3.x\basic_example) with oemof v0.3.1 and Python 3.7.3. It actually works fine.

However, I do not understand what was modified in your code. Line 68 in basic_example.py is the import of matplotlib, as far as I see. Did you try to run the example without any modifications?

**Comment by oakca** [comment] 2019-06-13 14:10
Hello Michael,

Can you maybe send your csv file, so that I can also check if it runs?

Additionally I also ran the `basic_example.py` and it works as @jakob-wo said.

**Comment by baumconsult** [comment] 2019-06-13 14:12
Hi Jakob,

sorry, I changed code in line 87:

#filename = os.path.join(os.path.dirname(__file__), 'basic_example.csv')
filename = 'basic_example.csv'

When running without that modification, the csv-file is not found.

The error message received after the modification is the following:

[cid:image001.jpg@01D52202.B93FC1E0]

I am using Python 3.7.0. Might that cause the problem?

Kind regards, Michael

Von: jakob-wo <notifications@github.com>
Gesendet: Donnerstag, 13. Juni 2019 16:00
An: oemof/oemof-examples <oemof-examples@noreply.github.com>
Cc: Michael Stöhr <m.Stoehr@baumgroup.de>; Author <author@noreply.github.com>
Betreff: Re: [oemof/oemof-examples] AttributeError: 'EnergySystem' object has no attribute 'signals' (#43)


Hi Michael,

I tried to reproduce what you did but I do not get an error mesage when running basic_example.py (oemof.solph\v0.3.x\basic_example) with oemof v0.3.1 and Python 3.7.3. It actually works fine.

However, I do not understand what was modified in your code. Line 68 in basic_example.py is the import of matplotlib, as far as I see. Did you try to run the example without any modifications?

**Comment by baumconsult** [comment] 2019-06-13 14:13
Yes, see attached.

Von: Okan Akca <notifications@github.com>
Gesendet: Donnerstag, 13. Juni 2019 16:11
An: oemof/oemof-examples <oemof-examples@noreply.github.com>
Cc: Michael Stöhr <m.Stoehr@baumgroup.de>; Author <author@noreply.github.com>
Betreff: Re: [oemof/oemof-examples] AttributeError: 'EnergySystem' object has no attribute 'signals' (#43)


Hello Michael,

Can you maybe send your csv file, so that I can also check if it runs?

Additionally I also ran the basic_example.py and it works as @jakob-wo<https://github.com/jakob-wo> said.

**Comment by baumconsult** [comment] 2019-06-13 14:18
I get the attached error message. The same happens when running other simple files which worked under v0.2.3.

Von: Okan Akca <notifications@github.com>
Gesendet: Donnerstag, 13. Juni 2019 16:17
An: oemof/oemof-examples <oemof-examples@noreply.github.com>
Cc: Michael Stöhr <m.Stoehr@baumgroup.de>; Author <author@noreply.github.com>
Betreff: Re: [oemof/oemof-examples] AttributeError: 'EnergySystem' object has no attribute 'signals' (#43)


Hello Michael,

from

sorry, I changed code in line 87:

I understand that you just changed this line #filename = os.path.join(os.path.dirname(__file__), 'basic_example.csv') to filename = 'basic_example.csv', so basically you are still using the same csv file. I did the same change, and it is still solving.

**Comment by uvchik** [comment] 2019-06-14 11:59
Why do you think it has to do with the csv-file. The error message comes from the new blinker.signals introduced in v0.3. What blinker version do you have installed? Did you install oemof 0.3.1 or did you update from v0.2.x?

**Comment by baumconsult** [comment] 2019-06-17 09:10
I have up-dated oemof in Anaconda Promt with "pip install oemof --upgrade" from v0.2.3 to v0.3.1

**Comment by baumconsult** [comment] 2019-06-17 09:36
By the way, basic_example.py runs now. I did not make any change except adapting:

 `nominal_capacity` to `nominal_storage_capacity`
  `initial_capacity` to `initial_storage_level`
  `capacity_loss` to `loss_rate`

**Comment by p-snft** [comment] 2019-06-17 11:36
To check whether these changes are made, we released v0.3.1. If this really the reason for the fail, I would suggest to close this issue but to open a new one: The error message should be more speaking.

**Comment by jakob-wo** [comment] 2019-06-17 11:49
I think there is no need for another Issue because this might belong to https://github.com/oemof/oemof/issues/514 (Error handling oemof app development).

**Closed** 2019-06-17 11:49 UTC
